better demo splash handling

diff --git a/test b/test
--- a/test
+++ b/test
@@ -1,6 +1,14 @@
 #!/bin/bash
 
 set -e
+
+# Check if activate.sh exists
+if [ ! -f "./activate.sh" ]; then
+    echo "Error: 'activate.sh' not found in the current directory. Have you installed the project? Try running './install'."
+    exit 1
+fi
+
+
 . ./activate.sh
 
 run_js_tests() {
